src/Entity/Artist.php
<?php

namespace App\Entity;

use App\Repository\ArtistRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArtistRepository::class)]
class Artist
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 40)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $thumbnail = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $biography = null;

    #[ORM\ManyToMany(targetEntity: Music::class, mappedBy: 'featuring')]
    private Collection $featurings;

    #[ORM\OneToMany(mappedBy: 'artist', targetEntity: Album::class, orphanRemoval: true)]
    private Collection $albums;

    public function __construct()
    {
        $this->featurings = new ArrayCollection();
        $this->albums = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }


    public function getThumbnail(): ?string
    {
        return $this->thumbnail;
    }

    public function setThumbnail(string $thumbnail): static
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }

    public function getBiography(): ?string
    {
        return $this->biography;
    }

    public function setBiography(string $biography): static
    {
        $this->biography = $biography;

        return $this;
    }

    /**
     * @return Collection<int, Music>
     */
    public function getFeaturings(): Collection
    {
        return $this->featurings;
    }

    public function addFeaturing(Music $featuring): static
    {
        if (!$this->featurings->contains($featuring)) {
            $this->featurings->add($featuring);
            $featuring->addFeaturing($this);
        }

        return $this;
    }

    public function removeFeaturing(Music $featuring): static
    {
        if ($this->featurings->removeElement($featuring)) {
            $featuring->removeFeaturing($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Album>
     */
    public function getAlbums(): Collection
    {
        return $this->albums;
    }

    public function addAlbum(Album $album): static
    {
        if (!$this->albums->contains($album)) {
            $this->albums->add($album);
            $album->setArtist($this);
        }

        return $this;
    }

    public function removeAlbum(Album $album): static
    {
        if ($this->albums->removeElement($album)) {
            // set the owning side to null (unless already changed)
            if ($album->getArtist() === $this) {
                $album->setArtist(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->name;
    }

}

src/Entity/Music.php
<?php

namespace App\Entity;

use App\Repository\MusicRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MusicRepository::class)]
class Music
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?DateTime $duration = null;

    #[ORM\ManyToMany(targetEntity: Artist::class, inversedBy: 'featurings')]
    private Collection $featuring;

    #[ORM\ManyToOne(inversedBy: 'music')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Album $album = null;

    public function __toString(): string
    {
        return $this->getTitle() ?? '';
    }

    public function __construct()
    {
        $this->featuring = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDuration(): ?DateTime
    {
        return $this->duration;
    }

    public function getDurationString(): string
    {
        if ($this->duration === null) {
            return '';
        }

        if ($this->duration->format('H') === '00') {
            return $this->duration->format('i:s');
        }

        return $this->duration->format('H:i:s');
    }

    public function setDuration(DateTime $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    /**
     * @return Collection<int, Artist>
     */
    public function getFeaturing(): Collection
    {
        return $this->featuring;
    }

    public function addFeaturing(Artist $featuring): static
    {
        if (!$this->featuring->contains($featuring)) {
            $this->featuring->add($featuring);
        }

        return $this;
    }

    public function removeFeaturing(Artist $featuring): static
    {
        $this->featuring->removeElement($featuring);

        return $this;
    }

    public function getAlbum(): ?Album
    {
        return $this->album;
    }

    public function setAlbum(?Album $album): static
    {
        $this->album = $album;

        return $this;
    }

}

src/Form/ArtistType.php
<?php

namespace App\Form;

use App\Entity\Artist;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArtistType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('thumbnail')
            ->add('biography')
            ->add('featurings')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Artist::class,
        ]);
    }
}

src/Controller/ArtistController.php
<?php

namespace App\Controller;

use App\Entity\Artist;
use App\Form\ArtistType;
use App\Repository\ArtistRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/artist')]
class ArtistController extends AbstractController
{
    #[Route('/', name: 'app_artist_index', methods: ['GET'])]
    public function index(ArtistRepository $artistRepository): Response
    {
        return $this->render('artist/index.html.twig', [
            'artists' => $artistRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_artist_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $artist = new Artist();
        $form = $this->createForm(ArtistType::class, $artist);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($artist);
            $entityManager->flush();

            return $this->redirectToRoute('app_artist_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('artist/new.html.twig', [
            'artist' => $artist,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_artist_show', methods: ['GET'])]
    public function show(Artist $artist)
    {
        $albums = $artist->getAlbums();
        $musics = [];
        foreach ($albums as $album) {
            $musics[] = $album->getMusic();
        }

        return $this->render('artist/show.html.twig', [
            'artist' => $artist,
            'albums' => $albums,
            'musics' => $musics,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_artist_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Artist $artist, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $form = $this->createForm(ArtistType::class, $artist);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_artist_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('artist/edit.html.twig', [
            'artist' => $artist,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_artist_delete', methods: ['POST'])]
    public function delete(Request $request, Artist $artist, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$artist->getId(), $request->request->get('_token'))) {
            $entityManager->remove($artist);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_artist_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/artist/_delete_form.html.twig
<form method="post" action="{{ path('app_artist_delete', {'id': artist.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ artist.id) }}">
    <button class="btn">Delete</button>
</form>

templates/artist/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/artist/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Artiste{% endblock %}

{% block body %}
    <h1>Modifier Artiste</h1>

    {{ include('artist/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_artist_index') }}">retour a la liste</a>

    {{ include('artist/_delete_form.html.twig') }}
{% endblock %}

templates/artist/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artiste{% endblock %}

{% block body %}
    <div class="container mx-auto px-4">
        <h1 class="text-4xl mb-4">Artiste</h1>

        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            {% for artist in artists %}
                <div class="bg-white shadow overflow-hidden sm:rounded-lg mb-4">
                    <div class="px-4 py-5 sm:px-6">
                        <h2 class="text-lg leading-6 font-medium text-gray-900">{{ artist.name }}</h2>
                    </div>
                    <div class="border-t border-gray-200">
                        <dl>
                            <div class="px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 w-60 h-60">
                                    <img class="object-cover w-60 h-60" src="{{ artist.thumbnail }}" alt="{{ artist.name }}">
                                </dd>
                            </div>
                            <div class="px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">Biography</dt>
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                    {{ artist.biography }}
                                </dd>
                            </div>
                        </dl>
                    </div>
                    <div class="px-4 py-4 sm:px-6">
                        <a href="{{ path('app_artist_show', {'id': artist.id}) }}" class="text-[#F0C033] hover:text-yellow-800">Voir</a>
                        <a href="{{ path('app_artist_edit', {'id': artist.id}) }}" class="text-[#F0C033] hover:text-yellow-800">Modifier</a>
                    </div>
                </div>
            {% else %}
                <div class="text-center py-4">Pas d'artiste trouvé</div>
            {% endfor %}
        </div>

        <a href="{{ path('app_artist_new') }}" class="bg-[#F0C033] hover:bg-[#D8A948] text-white font-bold py-2 px-4 rounded">Crée nouveau</a>
    </div>
{% endblock %}

templates/artist/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvel Artist{% endblock %}

{% block body %}
    <h1 class="text-2xl font-bold mb-4 text-center">Nouvel Artist</h1>

    <div class="w-full max-w-md mx-auto bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {{ form_start(form, {'attr': {'class': 'space-y-4'}}) }}
            {{ form_widget(form) }}
            <button type="submit" class="bg-[#F0C033] hover:bg-[#D8A948] text-white font-bold py-2 px-4 rounded">Crée</button>
        {{ form_end(form) }}
    </div>

    <a href="{{ path('app_artist_index') }}" class="text-[#F0C033] hover:text-yellow-800">retour a la liste</a>
{% endblock %}

templates/artist/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artiste{% endblock %}

{% block body %}
    <div class="container mx-auto px-4">
        <h1 class="text-4xl mb-4">Artiste</h1>
        <div class="bg-white shadow overflow-hidden sm:rounded-lg mb-4">
            <div class="px-4 py-5 sm:px-6">
                <h2 class="text-lg leading-6 font-medium text-gray-900">{{ artist.name }}</h2>
                <p class="mt-1 max-w-2xl text-sm text-gray-500">{{ artist.biography }}</p>
            </div>
            <div class="border-t border-gray-200">
                <dl>
                    <div class="px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 ">
                            <img src="{{ artist.thumbnail }}" alt="{{ artist.name }}">
                        </dd>
                    </div>
                </dl>
            </div>
            <h2 class="text-2xl my-4">Albums</h2>
            <div class="flex flex-wrap bg-white shadow overflow-hidden sm:rounded-lg mb-8 mr-4">
                {% for album in albums %}
                    <div class="">
                        <div class="px-4 py-5 sm:px-6 border-r">
                            <h3 class="text-lg leading-6 font-medium text-gray-900">{{ album.title }}</h3>
                        </div>
                        <div class="border-y border-r border-gray-200">
                            <dl>
                                <div class="px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                        <img class="w-52 h-52" src="{{ album.thumbnail }}" alt="{{ album.title }}">
                                    </dd>
                                </div>
                            </dl>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <h3 class="text-2xl my-4">Musique</h3>
            {% for album in albums %}
                {% for music in album.music %}
                    <div class="px-4 py-5 sm:px-6 flex justify-between {% if loop.index is odd %}bg-gray-100{% endif %}">
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 font-bold text-lg">{{ music.title }}</dd>
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ music.durationString }}</dd>
                    </div>
                {% endfor %}
            {% endfor %}
        </div>
        <a href="{{ path('app_artist_index') }}"
           class="bg-[#F0C033] hover:bg-[#D8A948] text-white font-bold py-2 px-4 rounded">Retour a la liste </a>
        <a href="{{ path('app_artist_edit', {'id': artist.id}) }}"
           class="bg-[#F0C033] hover:bg-[#D8A948] text-white font-bold py-2 px-4 rounded">Modifier</a>
        {{ include('artist/_delete_form.html.twig') }}
    </div>
{% endblock %}