src/Entity/Album.php
<?php

namespace App\Entity;

use App\Repository\AlbumRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AlbumRepository::class)]
class Album
{
    const Album = 1;
    const EP = 2;
    const SINGLE = 3;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $releasedate = null;

    #[ORM\Column]
    private ?int $type = null;

    #[ORM\Column(length: 255)]
    private ?string $thumbnail = null;

    #[ORM\ManyToOne(inversedBy: 'albums')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Artist $artist = null;

    #[ORM\OneToMany(mappedBy: 'album', targetEntity: Music::class, orphanRemoval: true)]
    private Collection $music;

    public function __construct()
    {
        $this->music = new ArrayCollection();
    }

    public function getTypeName(): string
    {
        switch ($this->type) {
            case self::Album:
                return 'Album';
            case self::EP:
                return 'EP';
            case self::SINGLE:
                return 'Single';
            default:
                return 'Unknown';
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getReleasedate(): ?\DateTimeInterface
    {
        return $this->releasedate;
    }

    public function setReleasedate(\DateTimeInterface $releasedate): static
    {
        $this->releasedate = $releasedate;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getThumbnail(): ?string
    {
        return $this->thumbnail;
    }

    public function setThumbnail(string $thumbnail): static
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }

    public function getArtist(): ?Artist
    {
        return $this->artist;
    }

    public function setArtist(?Artist $artist): static
    {
        $this->artist = $artist;

        return $this;
    }

    /**
     * @return Collection<int, Music>
     */
    public function getMusic(): Collection
    {
        return $this->music;
    }

    public function addMusic(Music $music): static
    {
        if (!$this->music->contains($music)) {
            $this->music->add($music);
            $music->setAlbum($this);
        }

        return $this;
    }

    public function removeMusic(Music $music): static
    {
        if ($this->music->removeElement($music)) {
            // set the owning side to null (unless already changed)
            if ($music->getAlbum() === $this) {
                $music->setAlbum(null);
            }
        }

        return $this;
    }
    public function __toString(): string
    {
        return $this->title;
    }
}

src/Form/AlbumType.php
<?php

namespace App\Form;

use App\Entity\Album;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AlbumType extends AbstractType
{
    private $type;

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('releasedate', BirthdayType::class, ['widget' => 'choice'])
            ->add('type', ChoiceType::class, [
        'choices' => [
            'Album' => Album::Album,
            'EP' => Album::EP,
            'Single' => Album::SINGLE,
        ],
    ])
        ->add('thumbnail')
        ->add('artist');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Album::class,
        ]);
    }
}

src/Controller/AlbumController.php
<?php

namespace App\Controller;

use App\Entity\Album;
use App\Form\AlbumType;
use App\Repository\AlbumRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/Album')]
class AlbumController extends AbstractController
{
    #[Route('/', name: 'app_album_index', methods: ['GET'])]
    public function index(AlbumRepository $albumRepository): Response
    {
        return $this->render('Album/index.html.twig', [
            'albums' => $albumRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_album_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $album = new Album();
        $form = $this->createForm(AlbumType::class, $album);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($album);
            $entityManager->flush();

            return $this->redirectToRoute('app_album_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('Album/new.html.twig', [
            'album' => $album,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_album_show', methods: ['GET'])]
    public function show(Album $album): Response
    {
        $artist = $album->getArtist();
        $musics = $album->getMusic();

        return $this->render('Album/show.html.twig', [
            'album' => $album,
            'artist' => $artist,
            'musics' => $musics,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_album_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Album $album, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $form = $this->createForm(AlbumType::class, $album);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_album_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('Album/edit.html.twig', [
            'album' => $album,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_album_delete', methods: ['POST'])]
    public function delete(Request $request, Album $album, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$album->getId(), $request->request->get('_token'))) {
            $entityManager->remove($album);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_album_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/Album/_delete_form.html.twig
<form method="post" action="{{ path('app_album_delete', {'id': album.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ album.id) }}">
    <button class="btn">Delete</button>
</form>

templates/Album/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/Album/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Album{% endblock %}

{% block body %}
    <h1>Modifier Album</h1>

    {{ include('Album/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_album_index') }}">retour a la liste</a>

    {{ include('Album/_delete_form.html.twig') }}
{% endblock %}

templates/Album/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Album{% endblock %}

{% block body %}
    <div class="container mx-auto px-4">
        <h1 class="text-4xl mb-4">Album</h1>

        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            {% for album in albums %}
                <div class="bg-white shadow overflow-hidden sm:rounded-lg mb-4">
                    <div class="px-4 py-5 sm:px-6">
                        <h2 class="text-lg leading-6 font-medium text-gray-900">{{ album.title }}</h2>
                    </div>
                    <div class="border-t border-gray-200">
                        <dl>
                            <div class="px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 w-60 h-60">
                                    <img class="object-cover w-60 h-60" src="{{ album.thumbnail }}" alt="{{ album.title }}">
                                </dd>
                            </div>
                            <div class="px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">Date de sortie</dt>
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                    {{ album.releasedate ? album.releasedate|date('d/m/Y') : '' }}
                                </dd>
                            </div>
                            <div class="px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">Type</dt>
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                    {{ album.typeName }}
                                </dd>
                            </div>
                        </dl>
                    </div>
                    <div class="px-4 py-4 sm:px-6">
                        <a href="{{ path('app_album_show', {'id': album.id}) }}" class="text-[#F0C033] hover:text-yellow-800">Voir</a>
                        <a href="{{ path('app_album_edit', {'id': album.id}) }}" class="text-[#F0C033] hover:text-yellow-800">Modifier</a>
                    </div>
                </div>
            {% else %}
                <div class="text-center py-4">Pas d'album trouvé</div>
            {% endfor %}
        </div>

        <a href="{{ path('app_album_new') }}" class="bg-[#F0C033] hover:bg-[#D8A948] text-white font-bold py-2 px-4 rounded">Crée nouveau</a>
    </div>
{% endblock %}

templates/Album/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvel Album{% endblock %}

{% block body %}
    <h1 class="text-2xl font-bold mb-4 text-center">Nouvel Album</h1>

    <div class="w-full max-w-md mx-auto bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {{ form_start(form, {'attr': {'class': 'space-y-4'}}) }}
            {{ form_widget(form) }}
            <button type="submit" class="bg-[#F0C033] hover:bg-[#D8A948] text-white font-bold py-2 px-4 rounded">Crée</button>
        {{ form_end(form) }}
    </div>

    <a href="{{ path('app_album_index') }}" class="text-[#F0C033] hover:text-yellow-800">retour a la liste</a>
{% endblock %}

templates/Album/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Album{% endblock %}

{% block body %}
    <div class="container mx-auto px-4 mt-4" >
        <div class="flex justify-content items-start" >
            <img class="w-14 h-14 rounded-full mb-4 mt-2" src="{{ artist.thumbnail }}" alt="{{ album.title }}" >
            <p class="font-bold text-lg px-2 m-2" >{{ artist.name }}</p >
        </div >
        <h1 class="text-4xl mb-4" >Album</h1 >

        <div class="bg-white shadow overflow-hidden sm:rounded-lg mb-4" >
            <div class="px-4 py-5 sm:px-6" >
                <h2 class="text-lg leading-6 font-medium text-gray-900" >{{ album.title }}</h2 >
            </div >
            <div class="border-t border-gray-200" >
                <dl >
                    <div class="px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6" >
                        <dt class="text-sm font-medium text-gray-500" >Miniature</dt >
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 w-80 h-80" >
                            <img class="w-60 h-72" src="{{ album.thumbnail }}" alt="{{ album.title }}" >
                        </dd >
                    </div >
                    <div class="px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6" >
                        <dt class="text-sm font-medium text-gray-500" >Date de sortie</dt >
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2" >
                            {{ album.releasedate ? album.releasedate|date('d/m/Y') : '' }}
                        </dd >
                    </div >
                    <div class="px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6" >
                        <dt class="text-sm font-medium text-gray-500" >Type</dt >
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2" >
                            {{ album.typeName }}
                        </dd >
                    </div >
                </dl >
            </div >
            <h2 class="text-2xl my-4" >Musique</h2 >
            {% for music in album.music %}
                <div class="px-4 py-5 sm:px-6 flex justify-between {% if loop.index is odd %}bg-gray-100{% endif %}" >
                    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 font-bold text-lg" >{{ music.title }}</dd >
                    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2" >{{ music.getDurationString() }}</dd >
                </div >
            {% else %}
                <div class="text-center py-4" >Pas de musique trouvé pour cet album</div >
            {% endfor %}
        </div >

        <a href="{{ path('app_album_index') }}"
           class="bg-[#F0C033] hover:bg-[#D8A948] text-white font-bold py-2 px-4 rounded" >Retour a la liste</a >
        <a href="{{ path('app_album_edit', {'id': album.id}) }}"
           class="bg-[#F0C033] hover:bg-[#D8A948] text-white font-bold py-2 px-4 rounded" >Modifier</a >

        {{ include('Album/_delete_form.html.twig') }}
    </div >
{% endblock %}